export const residentFieldLabels = {
  name: "Nama Penduduk",
  gender: "Jenis Kelamin",
  age: "Usia",
  height: "Tinggi Badan",
  weight: "Berat Badan",
  family_history_with_overweight: "Riwayat Keluarga Obesitas",
  favc: "Konsumsi Fast Food",
  fcvc: "Frekuensi Konsumsi Sayur",
  ncp: "Jumlah Makan Utama",
  caec: "Makanan di Antara Waktu Makan",
  smoke: "Merokok",
  ch2o: "Konsumsi Air Harian",
  scc: "Mengontrol Kalori",
  faf: "Frekuensi Aktivitas Fisik",
  tue: "Durasi Penggunaan Perangkat Teknologi",
  calc: "Konsumsi Alkohol",
  mtrans: "Jenis Transportasi",
};

export const residentFormFields = [
  "name",
  "gender",
  "age",
  "height",
  "weight",
  "family_history_with_overweight",
  "favc",
  "fcvc",
  "ncp",
  "caec",
  "smoke",
  "ch2o",
  "scc",
  "faf",
  "tue",
  "calc",
  "mtrans",
];
